### ISSUE TITLE
discuss metadata for products level 2 (images & videos)

### ISSUE THREAD

**Issue by Rebeca98** [biometrioearth/DM-issues-daily-stand-ups#18]
discuss metadata for video and images

**Comment by Rebeca98** [comment]
{'id': '_DEFAULT_!8000000000142d62',
 'cm_name': 'b56223439f9ca577349010ccbd33ffdb_0033.mp4',
 'cm_versionLabel': '1.0',
 'cm_versionType': 'MAJOR',
 'sipecam_VideoBitsPerPixel': 24,
 'sipecam_PixelsPerMeterY': '0',
 'sipecam_StreamCount': 2,
 'sipecam_Planes': 1,
 'sipecam_AudioSampleRate': '16.0 kHz',
 'sipecam_Endianness': 'Little endian',
 'sipecam_ImageWidth': 1024,
 'sipecam_DateDeployment': '2022-01-25T00:00:00Z',
 'sipecam_BitRate': '5.8 Mbit/sec',
 'sipecam_NumChannels': 1,
 'sipecam_FileSize': 4600000,
 'sipecam_CentroidCumulusLongitude': -95.85693,
 'sipecam_BitsPerSample': 16.0,
 'sipecam_Encoding': 'Microsoft PCM',
 'sipecam_NumImportantColors': 'All',
 'sipecam_ImageHeight': 720,
 'sipecam_NodeCategoryIntegrity': 'Integro',
 'sipecam_SerialNumber': 'HLPXGM09048640',
 'sipecam_Longitude': -95.6946,
 'sipecam_ImageLength': '2211840',
 'sipecam_NomenclatureNode': '1_22_1_821',
 'sipecam_Latitude': 17.0339,
 'sipecam_EcosystemsName': 'Bosques templados',
 'sipecam_MaxDataRate': 26542080,
 'sipecam_FrameRate': 12,
 'sipecam_AvgBytesPerSec': 32050.0,
 'sipecam_Megapixels': 0.73728,
 'sipecam_PixelsPerMeterX': '0',
 'sipecam_Duration': 6.32,
 'sipecam_LongitudeRef': 'West',
 'sipecam_BMPVersion': 'Windows V3',
 'sipecam_NumColors': 'Use BitDepth',
 'sipecam_AudioSampleCount': 0,
 'sipecam_AudioCompression': 'Microsoft Pulse Code Modulation (PCM)',
 'sipecam_LatitudeRef': 'North',
 'sipecam_AudioCompressionRate': '1.0x',
 'sipecam_CumulusName': '22',
 'sipecam_CentroidCumulusLatitude': 17.01282,
 'sipecam_FrameCount': 79,
 'sipecam_DateTimeOriginal': '2022-02-25T23:43:23Z',
 'sipecam_VideoCompression': 'Motion JPEG DIB (fourcc:"MJPG")',
 'sipecam_AudioBitRate': '256.4 Kbit/sec',
 'sipecam_DateDeployment_unit_of_time_day_of_year': 25,
 'sipecam_DateTimeOriginal_unit_of_time_day_of_month': 25,
 'sipecam_DateDeployment_unit_of_time_year': 2022,
 'sipecam_DateDeployment_unit_of_time_quarter': 1,
 'sipecam_DateTimeOriginal_unit_of_time_minute': 43,
 'sipecam_DateDeployment_unit_of_time_day_of_month': 25,
 'sipecam_DateTimeOriginal_unit_of_time_quarter': 1,
 'sipecam_DateTimeOriginal_unit_of_time_month': 2,
 'sipecam_DateTimeOriginal_unit_of_time_hour': 23,
 'sipecam_DateTimeOriginal_unit_of_time_day_of_year': 56,
 'sipecam_DateDeployment_unit_of_time_month': 1,
 'sipecam_DateDeployment_unit_of_time_day_of_week': 2,
 'sipecam_DateTimeOriginal_unit_of_time_year': 2022,
 'sipecam_DateTimeOriginal_unit_of_time_second': 23,
 'sipecam_DateTimeOriginal_unit_of_time_day_of_week': 5}

**Comment by palmoreck** [comment]
@Rebeca98 need to split discussion:

* metadata for images
* metadata for frames 
* metadata for videos

**Comment by palmoreck** [comment]
@Rebeca98 Regarding frames. One option is:

```
VideoReference: 'b56223439f9ca577349010ccbd33ffdb_0033.mp4',
Bbox: ['375,298,107,271'],
ImageWidth: ...,
DateDeployment: ...,
CentroidCumulusLongitude: ...,
ImageHeight: ...,
NodeCategoryIntegrity: ...,
SerialNumber: ...,
Longitude: ...,
ImageLength: ...,
NomenclatureNode: ...,
Latitude: ...,
EcosystemsName: ...,
LongitudeRef: ...,
LatitudeRef: ...,
CumulusName: ...,
DateTimeOriginal: ...,

```

**Comment by Rebeca98** [comment]
ImageWidth lo obtiene de los datos crudos @jdonlucas

**Comment by palmoreck** [comment]
Will not save metadata for products level 2 in tables
