### ISSUE TITLE
Migration of Zendro in CONABIO Github Org to B.e Github Org

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DM-issues-daily-stand-ups#2]

**Comment by jdonlucas** [comment]
I moved the code to the repo: https://github.com/biometrioearth/sipecamZendro, and restored the db in an ec2 instance. The following are the URL's in which zendro is exposed:

Graphiql: http://34.213.56.194/sipecam-zendro-graphiql/
SPA: http://34.213.56.194/sipecam-zendro-spa/
GraphQL: http://34.213.56.194/sipecam-zendro-graphql/
