### ISSUE TITLE
ELK - Grafana - Charts - Logs 

### ISSUE THREAD

**Issue by omaranda** [biometrioearth/DM-issues-daily-stand-ups#21]
Tools to track pufferfish status:

- Elasticsearch Logstash Kibana supported up to version 7 due to license change
- Opensearch AWS managed service
- Grafana consuming a table in a DB with the counts that I currently do manually or perhaps by parsing the logs.

Referencias:
- [Indexing with Elasticsearch](https://aws.amazon.com/blogs/database/indexing-metadata-in-amazon-elasticsearch-service-using-aws-lambda-and-python/)
- [Opensearch service](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/integrations.html#integrations-s3-lambda)

**Comment by omaranda** [comment]
References:
- [Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html)
- [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-installation-configuration.html)

**Comment by omaranda** [comment]
Best stack with docker for ELK with a lot of features to let it without any payment.

[elastdocker](https://github.com/sherifabdlnaby/elastdocker)

**Comment by omaranda** [comment]
1- how it works:

a) a csv can be generated as a rotating log, which is overwritten each time a new delivery is processed, which will be processed each time it receives entries.

We can design it as we want, defining the columns and their content.

b) the process is as follows:

the log / csv is generated => logstash reads it and indexes it with elastic search => that data is added to a previously designed dashboard.

2- how is it done?

once elk is installed:

an index is defined from the kibana development console, mapping the csv columns, example:

```
PUT /clusters
{
	"mappings": {
		"properties": {
			"id": {"type": "integer"},
			"name": {"type": "text"},
			"geometry": {"type": "geo_point"},
			"criteria_id": {"type": "text"},
			"user_ids": {"type": "text"},
			"ecosystems": {"type": "integer"},
			"con_socio": {"type": "boolean"},
		}
	}
}

```
then the ETL process is designed in a configuration file that will be sent to logstash, which can be scheduled to be constantly launched from a cron or when a processing task is launched.

The ETL has 3 phases:
- entry
- filter
- output

In the following examples I describe how the configuration file for logstash is defined.

Let's think that the file is called pipeline.conf
```
input {
	file {
		path => "./clusters.csv",
		start_position => beginning
	}
}

filter {
	csv {
		columns => ["id", "name", "geometry", "criteria_id", "user_ids", "ecosystem_id", "con_socio"]
	}
	mutate {
		add_field => {
			"simple_sample" => "%{column0},%{columns6}"
		}
	remove_field => ["message", "@version", "@timestamp", "host", "path"]	
	}
}

output {
	stdout { }

	elasticsearch {
		index => "clusters"
	}
}

```
configuration to process CSV file

- input: tells it which file to read and from where, in this case it indicates from the beginning so that it is rotating.

- filter: by default, logstash names columns from 0 to n, in this example I tell it to rename them.

- mutate: just for testing, I create a new column called simple_sample and there it stores the union of 2 columns

- remove_field: I remove the fields that logstash adds by default, it's not necessary, but I'm testing.

- output: standard output to see in the console and then the output is sent to elasticsearch

To start the process, you just have to execute the command passing the configuration file

```
bin/logstash pipeline.conf

```

Let's think that the file is called aaaa

```
input 
{
    file 
    {
       codec => multiline
        {
            pattern => '^\{'
            negate => true
            what => previous                
        }
        path => "/path/file.json"
        start_position => "beginning"       
        sincedb_path => "/path/null"
        exclude => "*.gz"
    }
}

filter {
json {
source => "message"
remove_field => ["path","@timestamp","@version","host","message"]
}
}

output {
  elasticsearch { hosts => ["localhost:9200"] 
  index => "logs"
  "document_type" => "json_from_logstash_simex"
  }
  stdout{}
}


```

Json format:

```
{"name":"blabla","ID":"1","TS":1351146569}
{"name":"blabla","ID":"1","TS":1351146569}
{"name":"blabla","ID":"1","TS":1351146569}
```
or any other

**Comment by omaranda** [comment]
Important note: logstash can read json, logs, csv and tables from any database, I'm thinking of reading the data particularly for file count dashboards from a single table, like the one we already have in the tochtli database.

and also generate the data that we want to count in a simpler and cleaner way and put it into a database, in very simple and flat tables.

what do you think?

**Comment by omaranda** [comment]
This is an explanation of the logstash configuration file for elasticsearch synchronization with the database.

Logstash pipeline configuration file structure contains three stages, input, filter and output. Within each stages there may be one or more plugins depending on the need for the pipeline.

```
input {
 #enables a specific source of events to be read by logstash
}
filter {
 # performs intermediary processing on an event
}
output {
 # send event data to a particular destination
}
```


As in this case there will be no data transformation, we will only have the input and filter stages.

For the input, as we will have to extract data from a database, we will use the [jdbc input](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html) plugin. The main part of the synchronization is in the input stage. Below is an example of how this stage should be set up to synchronize data with postgres and just below the explanation of all the config options.

```
input {
    jdbc {
        jdbc_connection_string => "jdbc:postgresql://localhost:5232"
        jdbc_user => "postgres"
        jdbc_password => "postgres"
        jdbc_driver_library => "/mnt/postgresql-42.2.1.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        statement_filepath => "/mnt/sipecam_files_proccessed.sql"
        tracking_column => "updated_at"
        tracking_column_type => "timestamp"
        use_column_value => true
        schedule => "* * * * *"
        last_run_metadata_path => "/mnt/.logstash_jdbc_last_run"
    }  
}

```

[jdbc_connection_string](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-jdbc_connection_string) is the database connection string.
[jdbc_user](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-jdbc_user) is the database user.
[jdbc_password](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-jdbc_password) is the password for the database user
[jdbc_driver_library](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-jdbc_driver_library) is the postgres connection JDBC driver.
[jdbc_driver_class](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-jdbc_driver_class) is the postgres JDBC driver class to be loaded.
[statement_filepath](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-statement_filepath) is the query path that will be executed against the database.
[tracking_column](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-tracking_column) is the query column that will be used to capture changes and send only changed or created records to elasticsearch.
[tracking_column_type](http://tracking_column_type/) specifies the data type of the column set in the tracking_column config, this option accepts numeric or timestamp. In our case, as we are going to identify the changes through a record update timestamp column, this option will be timestamp.
[use_column_value](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-use_column_value) enables synchronization through the field set in the tracking_column config.
[schedule](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-schedule) is the execution schedule of the pipeline's jdbc plugin, this option follows the linux cron pattern. In our case, the input is scheduled to be executed every minute.
[last_run_metadata_path](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-last_run_metadata_path) specifies a file where the last executed record of the column specified in tracking_column is recorded, in our case the updated_at column.
If the tracking_column is an update date of the row, the query must have an order by asc by this date, otherwise the data will not be synchronized correctly.

If the query retrieves a lot of information, you can use a [limit](https://www.postgresql.org/docs/8.1/queries-limit.html) clause on the query. If needed the pipeline can be executed every second. To do this, just add one more * to the schedule.

Still on the last_run_metadata_path, logstash creates a file where the last value of the tracking_column [updated_at] will be saved, with each execution of the pipeline the logstash overwrites the file and stores the last value of the tracking_column [updated_at].

As the query has an order by updated_at asc clause, it will be executed and the logstash will iterate and save the file every minute. Let's imagine that the value that the logstash retrieved was '2019–06–01T23: 07: 12.034'.

In the next run - after one minute - logstash will pass this value as a parameter for the query, retrieving only those records where the tracking_column [updated_at] is greater than '2019–06–01T23: 07: 12.034', and so on in every run .

At this point you may be wondering, how does logstash manage to pass the value that is in last_run_metadata_path ["/mnt/.logstash_jdbc_last_run"] within the query as a filter.

Here is an example of how the query would look inside the file set in the jdbc input option in /mnt/sipecam_files_proccessed.sql.


```
select * from files where updated_at > :sql_last_value 
order by updated_at asc limit 1000
```

The parameter: sql_last_value inside the query is responsible for sending the value saved in the .logstash_jdbc_last_run file and always keeping the updates running smoothly.

Now, add the output stage to your configuration file. The file will be like the example below.

```
input {
    jdbc {
        jdbc_connection_string => "jdbc:postgresql://localhost:5232"
        jdbc_user => "postgres"
        jdbc_password => "postgres"
        jdbc_driver_library => "/mnt/postgresql-42.2.1.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        statement_filepath => "/mnt/users.sql"
        tracking_column => "updated_at"
        tracking_column_type => "timestamp"
        use_column_value => true
        schedule => "* * * * *"
        last_run_metadata_path => "/mnt/.logstash_jdbc_last_run"
    }  
}
output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "sipecam_files_proccessed"
        document_id => "%{[id]}"
    }
}
```

In order to update the document instead of creating a new one, there is a need to set the [document_id](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-document_id) option to an unique key of the query output as configured above.

Lastly, just run logstash with -f option pointing to your configuration file.

To ensure that data is not lost, it is important to implement Persistent Queues and Dead Letter Queues. Implementation information for these logstash features can be found in the official documentation at https://www.elastic.co/guide/en/logstash/current/resiliency.html

---

**Comment by palmoreck** [comment]
Need to document ELK deployment with all the dashboards @omaranda
