### ISSUE TITLE
Kibana need to display data of SiPeCaM in a map (Leandro's request)

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DM-issues-daily-stand-ups#28]

**Comment by omaranda** [comment]
https://52.30.165.186:5601

u: readonly
p:000999........

**Comment by omaranda** [comment]
I create 2 maps:

- The fist one only with audio files
- The second one with 3 type of files

both can filter by:

- cluster name
- ecosystem
- file type
- period of time

unsing the map, dropdown controls, calendar and bar chart to select the time frame.

The map has 4 layers:

1. ANP's
2. clusters (polygons)
3. Nodes (points)
4. Devices (points)



![Image](https://user-images.githubusercontent.com/4795507/223757559-ffe6e3a7-2b29-4b4e-811a-6dc910ec7563.png)

**Comment by omaranda** [comment]
On this screenshot we can see how the map shows only the count of the data collected on cluster number 92.

- First with all files: 

![Image](https://user-images.githubusercontent.com/4795507/223758947-8271b03d-7d47-4bf0-9886-73ee9daa52ef.png)


- The second one is filtering  by audio type files:

![Image](https://user-images.githubusercontent.com/4795507/223759004-7287adcc-8604-4cbd-b383-9400c09d7d9c.png)

**Comment by omaranda** [comment]
Here the update:

- New dataset with only dates (YYYY-MM-DD)
- New layers: Nodes degradaded and preserved

<img width="1255" alt="Screenshot 2023-03-10 at 10 44 16" src="https://user-images.githubusercontent.com/4795507/224374188-e7d576ec-0fac-4756-8eaa-c89abe47d299.png">

**Comment by palmoreck** [comment]
Leandro is checking

**Comment by palmoreck** [comment]
Leandro is happy with the delivery
