### ISSUE TITLE
In diagram replace servers which are in Conabio with AWS, IONOS servers (1)

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DM-issues-daily-stand-ups#3]
Diagram: [sipecam_data_flow](https://app.diagrams.net/#G1ee66UtMlF8IQ2I2UJ2QtRyB9-0jZo3L_) will be a reference for diagram [sipecam_data_flow_restructured](https://app.diagrams.net/#G1OAbHz6fVMm5wBspYp7HbJEQcUBrsmAPU) which will replace Conabio servers with AWS or IONOS servers if we deem feasible. 

This will be done for data reception and data upload to AWS Open data account and AWS Conabio credits account

**Comment by omaranda** [comment]
I generated a proposal on the diagram, trying to be more clear and attached to the access to resources in AWS

**Comment by palmoreck** [comment]
need to check 

[sipecam_data_flow_restructured.drawio](https://app.diagrams.net/#G1OAbHz6fVMm5wBspYp7HbJEQcUBrsmAPU)

@palmoreck

**Comment by palmoreck** [comment]
We are not using Fargate. Diagram referred in this issue is lacking pufferfish functionalities. See: https://github.com/biometrioearth/pufferfish
