### ISSUE TITLE
LoadBalancer proposal to Thilo for MADxxx integration with in-situ system

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DM-issues-daily-stand-ups#31]
Include in proposal also pufferfish, kubearth, balam, reporting systems processes

**Comment by omaranda** [comment]
Here the first proposal, the diagram it's shared on the gdrive, I left here the link and an image

https://drive.google.com/file/d/1PRSBr1ymuS2daq5KBRoPCPGfsOzdZJWt/view?usp=share_link


<img width="608" alt="Screenshot 2023-03-09 at 9 44 09" src="https://user-images.githubusercontent.com/4795507/224076693-2bd8eea7-1cf6-4e38-b44b-c37ec4118b17.png">

**Comment by omaranda** [comment]
Thilo's answer 

<img width="451" alt="grafik" src="https://user-images.githubusercontent.com/4795507/225051051-cf01fcdf-cd1a-4d5c-a43a-05617a6396b7.png">

**Comment by palmoreck** [comment]
@omaranda i think we could start with Route53 and certificates

**Comment by omaranda** [comment]
I try but the user sys_admin doesn't have permissions on that services
