### ISSUE TITLE
Revision of RabbitMQ, AmazonMQ, ActiveMQ

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DM-issues-daily-stand-ups#32]
Will help to start discussions, designing and implementing tools for message send/receive processes

**Comment by Danahirmt** [comment]
AmanzonMQ is how RabbitMQ can live on aws and AmazonSQS is the replace for RabbitMQ

**Comment by palmoreck** [comment]
excellent. Will close this issue 
Thanks
