### ISSUE TITLE
Propose how to centralize scripts into 1 or 2 repositories for data management system

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DM-issues-daily-stand-ups#4]
there are some repositories in Conabio that uploads, process and extracts information from data files (wav, avi, jpg). Need to come up with ideas to centralize them into 1 or 2 repositories of biometrioearth Github Org

**Comment by jdonlucas** [comment]
Done, centralized in Tochtli repo: https://github.com/biometrioearth/tochtli
