### ISSUE TITLE
Grant Privileges on madxxx account to root account route53 services.

### ISSUE THREAD

**Issue by omaranda** [biometrioearth/DM-issues-daily-stand-ups#42]
The DNS, certificate and zones are configured and ready, but it's neccesary to grant privileges on madxxx account.

**Comment by palmoreck** [comment]
Some refs that could help:

https://sst.dev/chapters/share-route-53-domains-across-aws-accounts.html

https://aws.amazon.com/blogs/security/simplify-dns-management-in-a-multiaccount-environment-with-route-53-resolver/

**Comment by palmoreck** [comment]
@omaranda will check first options for giving access to madxxx account to Route53 configs

**Comment by palmoreck** [comment]
user for @omaranda was created in IAM center and was added to madxxx account. It has the permissions defined internally

**Comment by omaranda** [comment]
The service it's already configured on madxxx account and reviewed by Thilo and give us the OK.

**Comment by palmoreck** [comment]
👍🏾
