### ISSUE TITLE
create docker images for DM

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DM-issues-daily-stand-ups#8]
Under biometrioearth dockerhub user will be these docker images

**Comment by omaranda** [comment]
- [ ] snmb_data docker subirlo a la cuenta biometrio
- [ ] kobo toolbox docker configurado para replicar copia de datos (Master / Slave) apuntando a PostgreSQL externo
- [ ] grafana docker con solr y fuentes de datos configuradas

**Comment by palmoreck** [comment]
Qué tendría el primero? `snmb_data` ? @omaranda

**Comment by omaranda** [comment]
Tiene las bases de datos productivas del snmb:

- snmb_development
- snmb_developmentV14
- especies

ahora estan en eomiranda/snmb son 14G

esto es lo que tiene:

`                                                   List of databases
       Name       |  Owner   | Encoding |  Collate   |   Ctype    | ICU Locale | Locale Provider |   Access privileges

------------------+----------+----------+------------+------------+------------+-----------------+----------------------
-
 especies         | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
 postgres         | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
 snmb_development | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
 snmb_testing_v14 | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
 template0        | postgres | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            | =c/postgres
+`

**Comment by omaranda** [comment]
Voy a mover grafana con Docker a una tarjeta independiente, para agregar pruebas con grafana administrado directo desde ASW

**Comment by palmoreck** [comment]
Creaste la tarjeta para grafana @omaranda  ?
La documentación de la creación del docker de Grafana va directo a la documentación de `pufferfish`

**Comment by omaranda** [comment]
Saque un ítem de la lista a tarjeta, pero fue antes de pufferfish

**Comment by palmoreck** [comment]
crearé una tarjeta para documentación de grafana @omaranda y te asigno

**Comment by palmoreck** [comment]
falta documentación de lo del snmb @omaranda

**Comment by palmoreck** [comment]
también hay un infys_postgres en biometrioearth dockerhub falta documentación @omaranda

**Comment by palmoreck** [comment]
Voy a cerrar esta tarjeta dado que hay varias imágenes de docker mezcladas (unas van al pufferfish, otras son de conabio exclusivamente)
